### ISSUE TITLE
Letters are missing, when use  final HTML compression

### ISSUE THREAD

**Issue by kapagatavot** [websharks/html-compressor#52]
When enable "Yes, compress (remove extra whitespace) in the final HTML code too." some Russian letters (like "Р") are missing.  Please fix it.

![html compression](https://cloud.githubusercontent.com/assets/10515960/5721447/81f629f2-9b3a-11e4-9ffb-863a3c8fcf2d.jpg)

**Comment by jaswsinc** [comment]
This could be caused by CSS or JavaScript not written with UTF-8 encoding. The HTML Compressor forces a CSS charset of `UTF-8`. Do you have a link to a page where this occurs so we can verify that?

**Comment by kapagatavot** [comment]
Hello. Here is site http://kapagatavot.lv/ with HTML Compression enabled (with - No, do not compress the final HTML code.). All css and js looks great. But, when I switch compression to "Yes, compress (remove extra whitespace) in the final HTML code too." change letter "Р" (russian letter) to "�" - here is cache copy https://www.dropbox.com/s/35k6au52brt3gsc/quick-cache-http.zip?dl=0

If you need live link i can setup site on subdomen.

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** The HTML Compressor now strips UTF-8  Byte Order Markers (BOMs) from CSS files generated by preprocessors such as Sass. Files consolidated by the HTML Compressor include an `@charset` rule already, making a BOM unnecessary. In fact, if BOMs are not stripped, some browsers will choke on portions of a consolidated CSS file, because a BOM could potentially appear in the middle of the file; i.e., at the _wrong_ place.

  _**Symptoms included:** mysterious missing styles in portions of the site, fonts not loading at all times, or font-based icons (e.g., FontAwesome) to render mystery glyphs instead of the icons._

**Comment by raamdev** [comment]
**ZenCache Pro v150821** has been released and includes changes from this GitHub Issue.

See the [ZenCache Pro v150821 announcement](http://zencache.com/zencache-pro-v150821-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#52).
